male(jongho).
male(suhwan).
male(yunchang).
male(jaehoon).
male(chungbu).
female(suyeon).
female(jina).
female(jinsun).
female(jisu).
brother(suhwan,suyeon).
brother(yunchang,jina).
sister(suyeon,suhwan).
sister(jina,yunchang).
sister(jina,jinsun).
sister(jinsun,jina).
parent_of(jina,suyeon).
parent_of(jina,suhwan).
parent_of(jongho,suhwan).
parent_of(jongho,suyeon).
parent_of(chungbu,jongho).
parent_of(jinsun,jaehoon).
parent_of(yunchang,jisu).

father(X,Y):-parent_of(X,Y),male(X).
mother(X,Y):-parent_of(X,Y),female(X).
son(X,Y):-parent_of(Y,X),male(X).
daughter(X,Y):-parent_of(Y,X),female(X).
grandfather(X,Z):-parent_of(X,Y),parent_of(Y,Z),male(X).
sibling(X,Y):-brother(X,Y);sister(X,Y);brother(Y,X);sister(Y,X).
aunt(X,Z):-sister(X,Y),parent_of(Y,Z).
uncle(X,Z):-brother(X,Y),parent_of(Y,Z).
cousin(X,Y):-parent_of(A,X),parent_of(B,Y),sibling(A,B).
spouse(X,Y):-parent_of(X,Z),male(X),parent_of(Y,Z),female(Y).

%%parent_of(X,Y):-parent_of(X,Z),sibling(Y,Z).
/*male(jerry).
male(stuart).
male(warren).
male(peter).
female(kather).
female(maryalice).
female(ann).
brother(jerry,stuart).
brother(jerry,kather).
brother(peter,warren).
sister(ann,maryalice).
sister(kather,jerry).
parent_of(warren,jerry).
parent_of(maryalice,jerry).*/
